name: habits_now_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.0
  table_calendar: ^3.0.6
  provider: ^6.0.3
  intl: ^0.17.0
  whatsapp_unilink: ^2.0.1+1
  flutter_slidable: ^0.6.0
  carousel_slider: ^4.1.1
  brasil_fields: ^1.4.5
  url_launcher: ^6.0.12
  sqflite: ^2.0.3
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  http: ^0.13.5
  dio: ^4.0.6
  hive_flutter: ^1.1.0
  lottie: ^1.4.2
  flutter_riverpod: ^1.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
  